// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/ynishi/gdean/service"
)

// Injectors from di.go:

func initializeIssueServerWithRepo(ctx context.Context) *service.IssueServiceServer {
	issueRepository := service.DefaultIssueRepository()
	issueServiceServer := service.DefaultIssueServiceServerWithRepo(ctx, issueRepository)
	return issueServiceServer
}

func initializeUserServerWithRepo(ctx context.Context) *service.UserServiceServer {
	issueRepository := service.DefaultIssueRepository()
	userServiceServer := service.DefaultUserServiceServerWithRepo(ctx, issueRepository)
	return userServiceServer
}
