// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: v1/gdeananalyze.proto

package v1

import (
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metrics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SumOfUse     int32   `protobuf:"varint,2,opt,name=sum_of_use,json=sumOfUse,proto3" json:"sum_of_use,omitempty"`
	MeanOfDuring int32   `protobuf:"varint,3,opt,name=mean_of_during,json=meanOfDuring,proto3" json:"mean_of_during,omitempty"`
	ErrorRate    float32 `protobuf:"fixed32,4,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_gdeananalyze_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_v1_gdeananalyze_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_v1_gdeananalyze_proto_rawDescGZIP(), []int{0}
}

func (x *Metrics) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Metrics) GetSumOfUse() int32 {
	if x != nil {
		return x.SumOfUse
	}
	return 0
}

func (x *Metrics) GetMeanOfDuring() int32 {
	if x != nil {
		return x.MeanOfDuring
	}
	return 0
}

func (x *Metrics) GetErrorRate() float32 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

type GetMetricsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []uint32 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *GetMetricsRequest) Reset() {
	*x = GetMetricsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_gdeananalyze_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsRequest) ProtoMessage() {}

func (x *GetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_gdeananalyze_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_v1_gdeananalyze_proto_rawDescGZIP(), []int{1}
}

func (x *GetMetricsRequest) GetIds() []uint32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetMetricsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metrics map[uint32]*Metrics `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *GetMetricsResponse) Reset() {
	*x = GetMetricsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_gdeananalyze_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsResponse) ProtoMessage() {}

func (x *GetMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_gdeananalyze_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetMetricsResponse) Descriptor() ([]byte, []int) {
	return file_v1_gdeananalyze_proto_rawDescGZIP(), []int{2}
}

func (x *GetMetricsResponse) GetMetrics() map[uint32]*Metrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type MetaBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Desc        string            `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	ParamDef    map[string]string `protobuf:"bytes,3,rep,name=param_def,json=paramDef,proto3" json:"param_def,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	IsAvailable bool              `protobuf:"varint,4,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
}

func (x *MetaBody) Reset() {
	*x = MetaBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_gdeananalyze_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetaBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaBody) ProtoMessage() {}

func (x *MetaBody) ProtoReflect() protoreflect.Message {
	mi := &file_v1_gdeananalyze_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaBody.ProtoReflect.Descriptor instead.
func (*MetaBody) Descriptor() ([]byte, []int) {
	return file_v1_gdeananalyze_proto_rawDescGZIP(), []int{3}
}

func (x *MetaBody) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetaBody) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *MetaBody) GetParamDef() map[string]string {
	if x != nil {
		return x.ParamDef
	}
	return nil
}

func (x *MetaBody) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

type Meta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MetaBody   *MetaBody              `protobuf:"bytes,2,opt,name=metaBody,proto3" json:"metaBody,omitempty"`
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
}

func (x *Meta) Reset() {
	*x = Meta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_gdeananalyze_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meta) ProtoMessage() {}

func (x *Meta) ProtoReflect() protoreflect.Message {
	mi := &file_v1_gdeananalyze_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meta.ProtoReflect.Descriptor instead.
func (*Meta) Descriptor() ([]byte, []int) {
	return file_v1_gdeananalyze_proto_rawDescGZIP(), []int{4}
}

func (x *Meta) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Meta) GetMetaBody() *MetaBody {
	if x != nil {
		return x.MetaBody
	}
	return nil
}

func (x *Meta) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Meta) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type GetMetaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetMetaRequest) Reset() {
	*x = GetMetaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_gdeananalyze_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMetaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetaRequest) ProtoMessage() {}

func (x *GetMetaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_gdeananalyze_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetaRequest.ProtoReflect.Descriptor instead.
func (*GetMetaRequest) Descriptor() ([]byte, []int) {
	return file_v1_gdeananalyze_proto_rawDescGZIP(), []int{5}
}

func (x *GetMetaRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetMetaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//	*GetMetaResponse_Meta
	//	*GetMetaResponse_Status
	Response isGetMetaResponse_Response `protobuf_oneof:"response"`
}

func (x *GetMetaResponse) Reset() {
	*x = GetMetaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_gdeananalyze_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMetaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetaResponse) ProtoMessage() {}

func (x *GetMetaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_gdeananalyze_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetaResponse.ProtoReflect.Descriptor instead.
func (*GetMetaResponse) Descriptor() ([]byte, []int) {
	return file_v1_gdeananalyze_proto_rawDescGZIP(), []int{6}
}

func (m *GetMetaResponse) GetResponse() isGetMetaResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *GetMetaResponse) GetMeta() *Meta {
	if x, ok := x.GetResponse().(*GetMetaResponse_Meta); ok {
		return x.Meta
	}
	return nil
}

func (x *GetMetaResponse) GetStatus() *status.Status {
	if x, ok := x.GetResponse().(*GetMetaResponse_Status); ok {
		return x.Status
	}
	return nil
}

type isGetMetaResponse_Response interface {
	isGetMetaResponse_Response()
}

type GetMetaResponse_Meta struct {
	Meta *Meta `protobuf:"bytes,1,opt,name=meta,proto3,oneof"`
}

type GetMetaResponse_Status struct {
	Status *status.Status `protobuf:"bytes,2,opt,name=status,proto3,oneof"`
}

func (*GetMetaResponse_Meta) isGetMetaResponse_Response() {}

func (*GetMetaResponse_Status) isGetMetaResponse_Response() {}

type CreateMetaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MetaBody *MetaBody `protobuf:"bytes,1,opt,name=metaBody,proto3" json:"metaBody,omitempty"`
}

func (x *CreateMetaRequest) Reset() {
	*x = CreateMetaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_gdeananalyze_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMetaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMetaRequest) ProtoMessage() {}

func (x *CreateMetaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_gdeananalyze_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMetaRequest.ProtoReflect.Descriptor instead.
func (*CreateMetaRequest) Descriptor() ([]byte, []int) {
	return file_v1_gdeananalyze_proto_rawDescGZIP(), []int{7}
}

func (x *CreateMetaRequest) GetMetaBody() *MetaBody {
	if x != nil {
		return x.MetaBody
	}
	return nil
}

type CreateMetaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//	*CreateMetaResponse_Meta
	//	*CreateMetaResponse_Status
	Response isCreateMetaResponse_Response `protobuf_oneof:"response"`
}

func (x *CreateMetaResponse) Reset() {
	*x = CreateMetaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_gdeananalyze_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMetaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMetaResponse) ProtoMessage() {}

func (x *CreateMetaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_gdeananalyze_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMetaResponse.ProtoReflect.Descriptor instead.
func (*CreateMetaResponse) Descriptor() ([]byte, []int) {
	return file_v1_gdeananalyze_proto_rawDescGZIP(), []int{8}
}

func (m *CreateMetaResponse) GetResponse() isCreateMetaResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *CreateMetaResponse) GetMeta() *Meta {
	if x, ok := x.GetResponse().(*CreateMetaResponse_Meta); ok {
		return x.Meta
	}
	return nil
}

func (x *CreateMetaResponse) GetStatus() *status.Status {
	if x, ok := x.GetResponse().(*CreateMetaResponse_Status); ok {
		return x.Status
	}
	return nil
}

type isCreateMetaResponse_Response interface {
	isCreateMetaResponse_Response()
}

type CreateMetaResponse_Meta struct {
	Meta *Meta `protobuf:"bytes,1,opt,name=meta,proto3,oneof"`
}

type CreateMetaResponse_Status struct {
	Status *status.Status `protobuf:"bytes,2,opt,name=status,proto3,oneof"`
}

func (*CreateMetaResponse_Meta) isCreateMetaResponse_Response() {}

func (*CreateMetaResponse_Status) isCreateMetaResponse_Response() {}

type PutMetaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MetaBody *MetaBody `protobuf:"bytes,2,opt,name=metaBody,proto3" json:"metaBody,omitempty"`
}

func (x *PutMetaRequest) Reset() {
	*x = PutMetaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_gdeananalyze_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutMetaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutMetaRequest) ProtoMessage() {}

func (x *PutMetaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_gdeananalyze_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutMetaRequest.ProtoReflect.Descriptor instead.
func (*PutMetaRequest) Descriptor() ([]byte, []int) {
	return file_v1_gdeananalyze_proto_rawDescGZIP(), []int{9}
}

func (x *PutMetaRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PutMetaRequest) GetMetaBody() *MetaBody {
	if x != nil {
		return x.MetaBody
	}
	return nil
}

type PutMetaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//	*PutMetaResponse_UpdateTime
	//	*PutMetaResponse_Status
	Response isPutMetaResponse_Response `protobuf_oneof:"response"`
}

func (x *PutMetaResponse) Reset() {
	*x = PutMetaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_gdeananalyze_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutMetaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutMetaResponse) ProtoMessage() {}

func (x *PutMetaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_gdeananalyze_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutMetaResponse.ProtoReflect.Descriptor instead.
func (*PutMetaResponse) Descriptor() ([]byte, []int) {
	return file_v1_gdeananalyze_proto_rawDescGZIP(), []int{10}
}

func (m *PutMetaResponse) GetResponse() isPutMetaResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *PutMetaResponse) GetUpdateTime() *timestamppb.Timestamp {
	if x, ok := x.GetResponse().(*PutMetaResponse_UpdateTime); ok {
		return x.UpdateTime
	}
	return nil
}

func (x *PutMetaResponse) GetStatus() *status.Status {
	if x, ok := x.GetResponse().(*PutMetaResponse_Status); ok {
		return x.Status
	}
	return nil
}

type isPutMetaResponse_Response interface {
	isPutMetaResponse_Response()
}

type PutMetaResponse_UpdateTime struct {
	UpdateTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=update_time,json=updateTime,proto3,oneof"`
}

type PutMetaResponse_Status struct {
	Status *status.Status `protobuf:"bytes,2,opt,name=status,proto3,oneof"`
}

func (*PutMetaResponse_UpdateTime) isPutMetaResponse_Response() {}

func (*PutMetaResponse_Status) isPutMetaResponse_Response() {}

type DeleteMetaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteMetaRequest) Reset() {
	*x = DeleteMetaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_gdeananalyze_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMetaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMetaRequest) ProtoMessage() {}

func (x *DeleteMetaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_gdeananalyze_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMetaRequest.ProtoReflect.Descriptor instead.
func (*DeleteMetaRequest) Descriptor() ([]byte, []int) {
	return file_v1_gdeananalyze_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteMetaRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteMetaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//	*DeleteMetaResponse_DeleteTime
	//	*DeleteMetaResponse_Status
	Response isDeleteMetaResponse_Response `protobuf_oneof:"response"`
}

func (x *DeleteMetaResponse) Reset() {
	*x = DeleteMetaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_gdeananalyze_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMetaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMetaResponse) ProtoMessage() {}

func (x *DeleteMetaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_gdeananalyze_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMetaResponse.ProtoReflect.Descriptor instead.
func (*DeleteMetaResponse) Descriptor() ([]byte, []int) {
	return file_v1_gdeananalyze_proto_rawDescGZIP(), []int{12}
}

func (m *DeleteMetaResponse) GetResponse() isDeleteMetaResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *DeleteMetaResponse) GetDeleteTime() *timestamppb.Timestamp {
	if x, ok := x.GetResponse().(*DeleteMetaResponse_DeleteTime); ok {
		return x.DeleteTime
	}
	return nil
}

func (x *DeleteMetaResponse) GetStatus() *status.Status {
	if x, ok := x.GetResponse().(*DeleteMetaResponse_Status); ok {
		return x.Status
	}
	return nil
}

type isDeleteMetaResponse_Response interface {
	isDeleteMetaResponse_Response()
}

type DeleteMetaResponse_DeleteTime struct {
	DeleteTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=delete_time,json=deleteTime,proto3,oneof"`
}

type DeleteMetaResponse_Status struct {
	Status *status.Status `protobuf:"bytes,2,opt,name=status,proto3,oneof"`
}

func (*DeleteMetaResponse_DeleteTime) isDeleteMetaResponse_Response() {}

func (*DeleteMetaResponse_Status) isDeleteMetaResponse_Response() {}

type GetMetaListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartId     uint32 `protobuf:"varint,1,opt,name=start_id,json=startId,proto3" json:"start_id,omitempty"`
	IsAvailable bool   `protobuf:"varint,2,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
}

func (x *GetMetaListRequest) Reset() {
	*x = GetMetaListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_gdeananalyze_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMetaListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetaListRequest) ProtoMessage() {}

func (x *GetMetaListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_gdeananalyze_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetaListRequest.ProtoReflect.Descriptor instead.
func (*GetMetaListRequest) Descriptor() ([]byte, []int) {
	return file_v1_gdeananalyze_proto_rawDescGZIP(), []int{13}
}

func (x *GetMetaListRequest) GetStartId() uint32 {
	if x != nil {
		return x.StartId
	}
	return 0
}

func (x *GetMetaListRequest) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

type GetMetaListIds struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []uint32 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *GetMetaListIds) Reset() {
	*x = GetMetaListIds{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_gdeananalyze_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMetaListIds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetaListIds) ProtoMessage() {}

func (x *GetMetaListIds) ProtoReflect() protoreflect.Message {
	mi := &file_v1_gdeananalyze_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetaListIds.ProtoReflect.Descriptor instead.
func (*GetMetaListIds) Descriptor() ([]byte, []int) {
	return file_v1_gdeananalyze_proto_rawDescGZIP(), []int{14}
}

func (x *GetMetaListIds) GetIds() []uint32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetMetaListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//	*GetMetaListResponse_Ids
	//	*GetMetaListResponse_Status
	Response isGetMetaListResponse_Response `protobuf_oneof:"response"`
}

func (x *GetMetaListResponse) Reset() {
	*x = GetMetaListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_gdeananalyze_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMetaListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetaListResponse) ProtoMessage() {}

func (x *GetMetaListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_gdeananalyze_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetaListResponse.ProtoReflect.Descriptor instead.
func (*GetMetaListResponse) Descriptor() ([]byte, []int) {
	return file_v1_gdeananalyze_proto_rawDescGZIP(), []int{15}
}

func (m *GetMetaListResponse) GetResponse() isGetMetaListResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *GetMetaListResponse) GetIds() *GetMetaListIds {
	if x, ok := x.GetResponse().(*GetMetaListResponse_Ids); ok {
		return x.Ids
	}
	return nil
}

func (x *GetMetaListResponse) GetStatus() *status.Status {
	if x, ok := x.GetResponse().(*GetMetaListResponse_Status); ok {
		return x.Status
	}
	return nil
}

type isGetMetaListResponse_Response interface {
	isGetMetaListResponse_Response()
}

type GetMetaListResponse_Ids struct {
	Ids *GetMetaListIds `protobuf:"bytes,1,opt,name=ids,proto3,oneof"`
}

type GetMetaListResponse_Status struct {
	Status *status.Status `protobuf:"bytes,2,opt,name=status,proto3,oneof"`
}

func (*GetMetaListResponse_Ids) isGetMetaListResponse_Response() {}

func (*GetMetaListResponse_Status) isGetMetaListResponse_Response() {}

type MaxEmvRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TowPData *TowPData `protobuf:"bytes,1,opt,name=towPData,proto3" json:"towPData,omitempty"`
}

func (x *MaxEmvRequest) Reset() {
	*x = MaxEmvRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_gdeananalyze_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaxEmvRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaxEmvRequest) ProtoMessage() {}

func (x *MaxEmvRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_gdeananalyze_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaxEmvRequest.ProtoReflect.Descriptor instead.
func (*MaxEmvRequest) Descriptor() ([]byte, []int) {
	return file_v1_gdeananalyze_proto_rawDescGZIP(), []int{16}
}

func (x *MaxEmvRequest) GetTowPData() *TowPData {
	if x != nil {
		return x.TowPData
	}
	return nil
}

type MaxEmvResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxEmv     int32                  `protobuf:"varint,1,opt,name=maxEmv,proto3" json:"maxEmv,omitempty"`
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
}

func (x *MaxEmvResponse) Reset() {
	*x = MaxEmvResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_gdeananalyze_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaxEmvResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaxEmvResponse) ProtoMessage() {}

func (x *MaxEmvResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_gdeananalyze_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaxEmvResponse.ProtoReflect.Descriptor instead.
func (*MaxEmvResponse) Descriptor() ([]byte, []int) {
	return file_v1_gdeananalyze_proto_rawDescGZIP(), []int{17}
}

func (x *MaxEmvResponse) GetMaxEmv() int32 {
	if x != nil {
		return x.MaxEmv
	}
	return 0
}

func (x *MaxEmvResponse) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

type TowPData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	P1     float32 `protobuf:"fixed32,1,opt,name=p1,proto3" json:"p1,omitempty"` // p2 = 1 - p1
	DataP1 []int32 `protobuf:"varint,2,rep,packed,name=dataP1,proto3" json:"dataP1,omitempty"`
	DataP2 []int32 `protobuf:"varint,3,rep,packed,name=dataP2,proto3" json:"dataP2,omitempty"`
}

func (x *TowPData) Reset() {
	*x = TowPData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_gdeananalyze_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TowPData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TowPData) ProtoMessage() {}

func (x *TowPData) ProtoReflect() protoreflect.Message {
	mi := &file_v1_gdeananalyze_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TowPData.ProtoReflect.Descriptor instead.
func (*TowPData) Descriptor() ([]byte, []int) {
	return file_v1_gdeananalyze_proto_rawDescGZIP(), []int{18}
}

func (x *TowPData) GetP1() float32 {
	if x != nil {
		return x.P1
	}
	return 0
}

func (x *TowPData) GetDataP1() []int32 {
	if x != nil {
		return x.DataP1
	}
	return nil
}

func (x *TowPData) GetDataP2() []int32 {
	if x != nil {
		return x.DataP2
	}
	return nil
}

var File_v1_gdeananalyze_proto protoreflect.FileDescriptor

var file_v1_gdeananalyze_proto_rawDesc = []byte{
	0x0a, 0x15, 0x76, 0x31, 0x2f, 0x67, 0x64, 0x65, 0x61, 0x6e, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x7a,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x67, 0x64, 0x65, 0x61, 0x6e, 0x2e, 0x76,
	0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x17, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7c, 0x0a, 0x07, 0x4d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x0a, 0x73, 0x75, 0x6d, 0x5f, 0x6f, 0x66,
	0x5f, 0x75, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x75, 0x6d, 0x4f,
	0x66, 0x55, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x6d, 0x65, 0x61, 0x6e, 0x5f, 0x6f, 0x66, 0x5f,
	0x64, 0x75, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x6d, 0x65,
	0x61, 0x6e, 0x4f, 0x66, 0x44, 0x75, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x61, 0x74, 0x65, 0x22, 0x25, 0x0a, 0x11, 0x47, 0x65, 0x74,
	0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x03, 0x69, 0x64, 0x73,
	0x22, 0xa8, 0x01, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69,
	0x63, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x67, 0x64, 0x65, 0x61, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x07, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x1a, 0x4d, 0x0a, 0x0c,
	0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x27,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x67, 0x64, 0x65, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xd1, 0x01, 0x0a, 0x08,
	0x4d, 0x65, 0x74, 0x61, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x65, 0x73, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63,
	0x12, 0x3d, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x5f, 0x64, 0x65, 0x66, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x67, 0x64, 0x65, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4d,
	0x65, 0x74, 0x61, 0x42, 0x6f, 0x64, 0x79, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x44, 0x65, 0x66,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x44, 0x65, 0x66, 0x12,
	0x21, 0x0a, 0x0c, 0x69, 0x73, 0x5f, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62,
	0x6c, 0x65, 0x1a, 0x3b, 0x0a, 0x0d, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x44, 0x65, 0x66, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22,
	0xc0, 0x01, 0x0a, 0x04, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2e, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61,
	0x42, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x64, 0x65,
	0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x08,
	0x6d, 0x65, 0x74, 0x61, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x3b, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x3b, 0x0a, 0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x22, 0x20, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x71, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x67, 0x64, 0x65, 0x61, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x4d, 0x65, 0x74, 0x61, 0x48, 0x00, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x12, 0x2c, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x0a, 0x0a, 0x08, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x43, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x08,
	0x6d, 0x65, 0x74, 0x61, 0x42, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x67, 0x64, 0x65, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x42, 0x6f,
	0x64, 0x79, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x42, 0x6f, 0x64, 0x79, 0x22, 0x74, 0x0a, 0x12,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x67, 0x64, 0x65, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x61,
	0x48, 0x00, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x12, 0x2c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x48, 0x00, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x50, 0x0a, 0x0e, 0x50, 0x75, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x2e, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x42, 0x6f, 0x64, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x64, 0x65, 0x61, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61,
	0x42, 0x6f, 0x64, 0x79, 0x22, 0x8a, 0x01, 0x0a, 0x0f, 0x50, 0x75, 0x74, 0x4d, 0x65, 0x74, 0x61,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0b, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x48, 0x00, 0x52, 0x0a, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x48, 0x00, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x23, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x8d, 0x01, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a,
	0x0b, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x48, 0x00,
	0x52, 0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x52, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x74,
	0x61, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x73, 0x5f, 0x61, 0x76,
	0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69,
	0x73, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x22, 0x0a, 0x0e, 0x47, 0x65,
	0x74, 0x4d, 0x65, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x64, 0x73, 0x12, 0x10, 0x0a, 0x03,
	0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x7d,
	0x0a, 0x13, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x67, 0x64, 0x65, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x4d, 0x65, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x64, 0x73, 0x48, 0x00, 0x52, 0x03,
	0x69, 0x64, 0x73, 0x12, 0x2c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x72, 0x70, 0x63,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3f, 0x0a,
	0x0d, 0x4d, 0x61, 0x78, 0x45, 0x6d, 0x76, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e,
	0x0a, 0x08, 0x74, 0x6f, 0x77, 0x50, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x67, 0x64, 0x65, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x6f, 0x77, 0x50,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x74, 0x6f, 0x77, 0x50, 0x44, 0x61, 0x74, 0x61, 0x22, 0x65,
	0x0a, 0x0e, 0x4d, 0x61, 0x78, 0x45, 0x6d, 0x76, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x78, 0x45, 0x6d, 0x76, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x6d, 0x61, 0x78, 0x45, 0x6d, 0x76, 0x12, 0x3b, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x4a, 0x0a, 0x08, 0x54, 0x6f, 0x77, 0x50, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x0e, 0x0a, 0x02, 0x70, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x70,
	0x31, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x61, 0x74, 0x61, 0x50, 0x31, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x05, 0x52, 0x06, 0x64, 0x61, 0x74, 0x61, 0x50, 0x31, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x61, 0x74,
	0x61, 0x50, 0x32, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x06, 0x64, 0x61, 0x74, 0x61, 0x50,
	0x32, 0x32, 0x82, 0x04, 0x0a, 0x0e, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x7a, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x12,
	0x18, 0x2e, 0x67, 0x64, 0x65, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65,
	0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x67, 0x64, 0x65, 0x61,
	0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4d, 0x65, 0x74, 0x61, 0x12, 0x1b, 0x2e, 0x67, 0x64, 0x65, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1c, 0x2e, 0x67, 0x64, 0x65, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x40, 0x0a, 0x07, 0x50, 0x75, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x18, 0x2e, 0x67,
	0x64, 0x65, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x67, 0x64, 0x65, 0x61, 0x6e, 0x2e, 0x76,
	0x31, 0x2e, 0x50, 0x75, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x74,
	0x61, 0x12, 0x1b, 0x2e, 0x67, 0x64, 0x65, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c,
	0x2e, 0x67, 0x64, 0x65, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4c,
	0x0a, 0x0b, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1c, 0x2e,
	0x67, 0x64, 0x65, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x61,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x67, 0x64,
	0x65, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0a,
	0x47, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x12, 0x1b, 0x2e, 0x67, 0x64, 0x65,
	0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x67, 0x64, 0x65, 0x61, 0x6e, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x06, 0x4d, 0x61, 0x78, 0x45, 0x6d,
	0x76, 0x12, 0x17, 0x2e, 0x67, 0x64, 0x65, 0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x61, 0x78,
	0x45, 0x6d, 0x76, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x67, 0x64, 0x65,
	0x61, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x61, 0x78, 0x45, 0x6d, 0x76, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1c, 0x5a, 0x1a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x6e, 0x69, 0x73, 0x68, 0x69, 0x2f, 0x67, 0x64, 0x65, 0x61,
	0x6e, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_gdeananalyze_proto_rawDescOnce sync.Once
	file_v1_gdeananalyze_proto_rawDescData = file_v1_gdeananalyze_proto_rawDesc
)

func file_v1_gdeananalyze_proto_rawDescGZIP() []byte {
	file_v1_gdeananalyze_proto_rawDescOnce.Do(func() {
		file_v1_gdeananalyze_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_gdeananalyze_proto_rawDescData)
	})
	return file_v1_gdeananalyze_proto_rawDescData
}

var file_v1_gdeananalyze_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_v1_gdeananalyze_proto_goTypes = []interface{}{
	(*Metrics)(nil),               // 0: gdean.v1.Metrics
	(*GetMetricsRequest)(nil),     // 1: gdean.v1.GetMetricsRequest
	(*GetMetricsResponse)(nil),    // 2: gdean.v1.GetMetricsResponse
	(*MetaBody)(nil),              // 3: gdean.v1.MetaBody
	(*Meta)(nil),                  // 4: gdean.v1.Meta
	(*GetMetaRequest)(nil),        // 5: gdean.v1.GetMetaRequest
	(*GetMetaResponse)(nil),       // 6: gdean.v1.GetMetaResponse
	(*CreateMetaRequest)(nil),     // 7: gdean.v1.CreateMetaRequest
	(*CreateMetaResponse)(nil),    // 8: gdean.v1.CreateMetaResponse
	(*PutMetaRequest)(nil),        // 9: gdean.v1.PutMetaRequest
	(*PutMetaResponse)(nil),       // 10: gdean.v1.PutMetaResponse
	(*DeleteMetaRequest)(nil),     // 11: gdean.v1.DeleteMetaRequest
	(*DeleteMetaResponse)(nil),    // 12: gdean.v1.DeleteMetaResponse
	(*GetMetaListRequest)(nil),    // 13: gdean.v1.GetMetaListRequest
	(*GetMetaListIds)(nil),        // 14: gdean.v1.GetMetaListIds
	(*GetMetaListResponse)(nil),   // 15: gdean.v1.GetMetaListResponse
	(*MaxEmvRequest)(nil),         // 16: gdean.v1.MaxEmvRequest
	(*MaxEmvResponse)(nil),        // 17: gdean.v1.MaxEmvResponse
	(*TowPData)(nil),              // 18: gdean.v1.TowPData
	nil,                           // 19: gdean.v1.GetMetricsResponse.MetricsEntry
	nil,                           // 20: gdean.v1.MetaBody.ParamDefEntry
	(*timestamppb.Timestamp)(nil), // 21: google.protobuf.Timestamp
	(*status.Status)(nil),         // 22: google.rpc.Status
}
var file_v1_gdeananalyze_proto_depIdxs = []int32{
	19, // 0: gdean.v1.GetMetricsResponse.metrics:type_name -> gdean.v1.GetMetricsResponse.MetricsEntry
	20, // 1: gdean.v1.MetaBody.param_def:type_name -> gdean.v1.MetaBody.ParamDefEntry
	3,  // 2: gdean.v1.Meta.metaBody:type_name -> gdean.v1.MetaBody
	21, // 3: gdean.v1.Meta.create_time:type_name -> google.protobuf.Timestamp
	21, // 4: gdean.v1.Meta.update_time:type_name -> google.protobuf.Timestamp
	4,  // 5: gdean.v1.GetMetaResponse.meta:type_name -> gdean.v1.Meta
	22, // 6: gdean.v1.GetMetaResponse.status:type_name -> google.rpc.Status
	3,  // 7: gdean.v1.CreateMetaRequest.metaBody:type_name -> gdean.v1.MetaBody
	4,  // 8: gdean.v1.CreateMetaResponse.meta:type_name -> gdean.v1.Meta
	22, // 9: gdean.v1.CreateMetaResponse.status:type_name -> google.rpc.Status
	3,  // 10: gdean.v1.PutMetaRequest.metaBody:type_name -> gdean.v1.MetaBody
	21, // 11: gdean.v1.PutMetaResponse.update_time:type_name -> google.protobuf.Timestamp
	22, // 12: gdean.v1.PutMetaResponse.status:type_name -> google.rpc.Status
	21, // 13: gdean.v1.DeleteMetaResponse.delete_time:type_name -> google.protobuf.Timestamp
	22, // 14: gdean.v1.DeleteMetaResponse.status:type_name -> google.rpc.Status
	14, // 15: gdean.v1.GetMetaListResponse.ids:type_name -> gdean.v1.GetMetaListIds
	22, // 16: gdean.v1.GetMetaListResponse.status:type_name -> google.rpc.Status
	18, // 17: gdean.v1.MaxEmvRequest.towPData:type_name -> gdean.v1.TowPData
	21, // 18: gdean.v1.MaxEmvResponse.create_time:type_name -> google.protobuf.Timestamp
	0,  // 19: gdean.v1.GetMetricsResponse.MetricsEntry.value:type_name -> gdean.v1.Metrics
	5,  // 20: gdean.v1.AnalyzeService.GetMeta:input_type -> gdean.v1.GetMetaRequest
	7,  // 21: gdean.v1.AnalyzeService.CreateMeta:input_type -> gdean.v1.CreateMetaRequest
	9,  // 22: gdean.v1.AnalyzeService.PutMeta:input_type -> gdean.v1.PutMetaRequest
	11, // 23: gdean.v1.AnalyzeService.DeleteMeta:input_type -> gdean.v1.DeleteMetaRequest
	13, // 24: gdean.v1.AnalyzeService.GetMetaList:input_type -> gdean.v1.GetMetaListRequest
	1,  // 25: gdean.v1.AnalyzeService.GetMetrics:input_type -> gdean.v1.GetMetricsRequest
	16, // 26: gdean.v1.AnalyzeService.MaxEmv:input_type -> gdean.v1.MaxEmvRequest
	6,  // 27: gdean.v1.AnalyzeService.GetMeta:output_type -> gdean.v1.GetMetaResponse
	8,  // 28: gdean.v1.AnalyzeService.CreateMeta:output_type -> gdean.v1.CreateMetaResponse
	10, // 29: gdean.v1.AnalyzeService.PutMeta:output_type -> gdean.v1.PutMetaResponse
	12, // 30: gdean.v1.AnalyzeService.DeleteMeta:output_type -> gdean.v1.DeleteMetaResponse
	15, // 31: gdean.v1.AnalyzeService.GetMetaList:output_type -> gdean.v1.GetMetaListResponse
	2,  // 32: gdean.v1.AnalyzeService.GetMetrics:output_type -> gdean.v1.GetMetricsResponse
	17, // 33: gdean.v1.AnalyzeService.MaxEmv:output_type -> gdean.v1.MaxEmvResponse
	27, // [27:34] is the sub-list for method output_type
	20, // [20:27] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_v1_gdeananalyze_proto_init() }
func file_v1_gdeananalyze_proto_init() {
	if File_v1_gdeananalyze_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_gdeananalyze_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Metrics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_gdeananalyze_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMetricsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_gdeananalyze_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMetricsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_gdeananalyze_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetaBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_gdeananalyze_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Meta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_gdeananalyze_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMetaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_gdeananalyze_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMetaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_gdeananalyze_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMetaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_gdeananalyze_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMetaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_gdeananalyze_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutMetaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_gdeananalyze_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutMetaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_gdeananalyze_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMetaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_gdeananalyze_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteMetaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_gdeananalyze_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMetaListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_gdeananalyze_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMetaListIds); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_gdeananalyze_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMetaListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_gdeananalyze_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaxEmvRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_gdeananalyze_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaxEmvResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_gdeananalyze_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TowPData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_v1_gdeananalyze_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*GetMetaResponse_Meta)(nil),
		(*GetMetaResponse_Status)(nil),
	}
	file_v1_gdeananalyze_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*CreateMetaResponse_Meta)(nil),
		(*CreateMetaResponse_Status)(nil),
	}
	file_v1_gdeananalyze_proto_msgTypes[10].OneofWrappers = []interface{}{
		(*PutMetaResponse_UpdateTime)(nil),
		(*PutMetaResponse_Status)(nil),
	}
	file_v1_gdeananalyze_proto_msgTypes[12].OneofWrappers = []interface{}{
		(*DeleteMetaResponse_DeleteTime)(nil),
		(*DeleteMetaResponse_Status)(nil),
	}
	file_v1_gdeananalyze_proto_msgTypes[15].OneofWrappers = []interface{}{
		(*GetMetaListResponse_Ids)(nil),
		(*GetMetaListResponse_Status)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_gdeananalyze_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_gdeananalyze_proto_goTypes,
		DependencyIndexes: file_v1_gdeananalyze_proto_depIdxs,
		MessageInfos:      file_v1_gdeananalyze_proto_msgTypes,
	}.Build()
	File_v1_gdeananalyze_proto = out.File
	file_v1_gdeananalyze_proto_rawDesc = nil
	file_v1_gdeananalyze_proto_goTypes = nil
	file_v1_gdeananalyze_proto_depIdxs = nil
}
