// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Analysis struct {
	ID      string `json:"id"`
	IssueID string `json:"issueId"`
}

type Branch struct {
	ID           string    `json:"id"`
	IssueID      string    `json:"issueId"`
	Title        string    `json:"title"`
	CreatedAt    time.Time `json:"createdAt"`
	LastModified time.Time `json:"lastModified"`
}

type Comment struct {
	ID           string    `json:"id"`
	IssueID      string    `json:"issueId"`
	AuthorID     string    `json:"authorId"`
	Content      string    `json:"content"`
	CreatedAt    time.Time `json:"createdAt"`
	LastModified time.Time `json:"lastModified"`
}

type Issue struct {
	ID               string      `json:"id"`
	Title            string      `json:"title"`
	Desc             string      `json:"desc"`
	AuthorName       string      `json:"authorName"`
	ContributerNames []string    `json:"contributerNames"`
	Comments         []*Comment  `json:"comments"`
	Branches         []*Branch   `json:"branches"`
	Analysis         []*Analysis `json:"analysis"`
	CreatedAtIso     time.Time   `json:"createdAtISO"`
	LastModifiedIso  string      `json:"lastModifiedISO"`
}

type IssueSummary struct {
	ID            string `json:"id"`
	Title         string `json:"title"`
	Desc          string `json:"desc"`
	AuthorName    string `json:"authorName"`
	MemberCount   int    `json:"memberCount"`
	CommentCount  int    `json:"commentCount"`
	BranchCount   int    `json:"branchCount"`
	AnalysisCount int    `json:"analysisCount"`
	CreatedAt     string `json:"createdAt"`
	LastModified  string `json:"lastModified"`
}

type NewComment struct {
	UserID  string `json:"userId"`
	Content string `json:"content"`
}

type NewIssue struct {
	Title    string   `json:"title"`
	Desc     *string  `json:"desc"`
	Branches []string `json:"branches"`
	UserID   string   `json:"userId"`
}

type PutComment struct {
	ID      string `json:"id"`
	UserID  string `json:"userId"`
	Content string `json:"content"`
}
