// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package gdean

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GDeanServiceClient is the client API for GDeanService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GDeanServiceClient interface {
	ReportMaxEmvResults(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportResponse, error)
}

type gDeanServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGDeanServiceClient(cc grpc.ClientConnInterface) GDeanServiceClient {
	return &gDeanServiceClient{cc}
}

func (c *gDeanServiceClient) ReportMaxEmvResults(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportResponse, error) {
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, "/gdean.GDeanService/ReportMaxEmvResults", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GDeanServiceServer is the server API for GDeanService service.
// All implementations must embed UnimplementedGDeanServiceServer
// for forward compatibility
type GDeanServiceServer interface {
	ReportMaxEmvResults(context.Context, *ReportRequest) (*ReportResponse, error)
	mustEmbedUnimplementedGDeanServiceServer()
}

// UnimplementedGDeanServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGDeanServiceServer struct {
}

func (UnimplementedGDeanServiceServer) ReportMaxEmvResults(context.Context, *ReportRequest) (*ReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportMaxEmvResults not implemented")
}
func (UnimplementedGDeanServiceServer) mustEmbedUnimplementedGDeanServiceServer() {}

// UnsafeGDeanServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GDeanServiceServer will
// result in compilation errors.
type UnsafeGDeanServiceServer interface {
	mustEmbedUnimplementedGDeanServiceServer()
}

func RegisterGDeanServiceServer(s grpc.ServiceRegistrar, srv GDeanServiceServer) {
	s.RegisterService(&GDeanService_ServiceDesc, srv)
}

func _GDeanService_ReportMaxEmvResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GDeanServiceServer).ReportMaxEmvResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gdean.GDeanService/ReportMaxEmvResults",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GDeanServiceServer).ReportMaxEmvResults(ctx, req.(*ReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GDeanService_ServiceDesc is the grpc.ServiceDesc for GDeanService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GDeanService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gdean.GDeanService",
	HandlerType: (*GDeanServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportMaxEmvResults",
			Handler:    _GDeanService_ReportMaxEmvResults_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gdean.proto",
}
