// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: pb/gdean.proto

package gdean

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxEmv     int32                  `protobuf:"varint,1,opt,name=maxEmv,proto3" json:"maxEmv,omitempty"`
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_gdean_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_pb_gdean_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_pb_gdean_proto_rawDescGZIP(), []int{0}
}

func (x *Result) GetMaxEmv() int32 {
	if x != nil {
		return x.MaxEmv
	}
	return 0
}

func (x *Result) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

type Report struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumberOfCalc int32     `protobuf:"varint,1,opt,name=numberOfCalc,proto3" json:"numberOfCalc,omitempty"`
	Result       []*Result `protobuf:"bytes,2,rep,name=result,proto3" json:"result,omitempty"`
}

func (x *Report) Reset() {
	*x = Report{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_gdean_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Report) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Report) ProtoMessage() {}

func (x *Report) ProtoReflect() protoreflect.Message {
	mi := &file_pb_gdean_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Report.ProtoReflect.Descriptor instead.
func (*Report) Descriptor() ([]byte, []int) {
	return file_pb_gdean_proto_rawDescGZIP(), []int{1}
}

func (x *Report) GetNumberOfCalc() int32 {
	if x != nil {
		return x.NumberOfCalc
	}
	return 0
}

func (x *Report) GetResult() []*Result {
	if x != nil {
		return x.Result
	}
	return nil
}

type TowPData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	P1     float32 `protobuf:"fixed32,1,opt,name=p1,proto3" json:"p1,omitempty"` // p2 = 1 - p1
	DataP1 []int32 `protobuf:"varint,2,rep,packed,name=dataP1,proto3" json:"dataP1,omitempty"`
	DataP2 []int32 `protobuf:"varint,3,rep,packed,name=dataP2,proto3" json:"dataP2,omitempty"`
}

func (x *TowPData) Reset() {
	*x = TowPData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_gdean_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TowPData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TowPData) ProtoMessage() {}

func (x *TowPData) ProtoReflect() protoreflect.Message {
	mi := &file_pb_gdean_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TowPData.ProtoReflect.Descriptor instead.
func (*TowPData) Descriptor() ([]byte, []int) {
	return file_pb_gdean_proto_rawDescGZIP(), []int{2}
}

func (x *TowPData) GetP1() float32 {
	if x != nil {
		return x.P1
	}
	return 0
}

func (x *TowPData) GetDataP1() []int32 {
	if x != nil {
		return x.DataP1
	}
	return nil
}

func (x *TowPData) GetDataP2() []int32 {
	if x != nil {
		return x.DataP2
	}
	return nil
}

type MaxEmvRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TowPData *TowPData `protobuf:"bytes,1,opt,name=towPData,proto3" json:"towPData,omitempty"`
}

func (x *MaxEmvRequest) Reset() {
	*x = MaxEmvRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_gdean_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaxEmvRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaxEmvRequest) ProtoMessage() {}

func (x *MaxEmvRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_gdean_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaxEmvRequest.ProtoReflect.Descriptor instead.
func (*MaxEmvRequest) Descriptor() ([]byte, []int) {
	return file_pb_gdean_proto_rawDescGZIP(), []int{3}
}

func (x *MaxEmvRequest) GetTowPData() *TowPData {
	if x != nil {
		return x.TowPData
	}
	return nil
}

type MaxEmvResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *Result `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *MaxEmvResponse) Reset() {
	*x = MaxEmvResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_gdean_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MaxEmvResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaxEmvResponse) ProtoMessage() {}

func (x *MaxEmvResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_gdean_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaxEmvResponse.ProtoReflect.Descriptor instead.
func (*MaxEmvResponse) Descriptor() ([]byte, []int) {
	return file_pb_gdean_proto_rawDescGZIP(), []int{4}
}

func (x *MaxEmvResponse) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

type ReportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReportRequest) Reset() {
	*x = ReportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_gdean_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRequest) ProtoMessage() {}

func (x *ReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_gdean_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRequest.ProtoReflect.Descriptor instead.
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return file_pb_gdean_proto_rawDescGZIP(), []int{5}
}

type ReportResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Report *Report `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
}

func (x *ReportResponse) Reset() {
	*x = ReportResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_gdean_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResponse) ProtoMessage() {}

func (x *ReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_gdean_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResponse.ProtoReflect.Descriptor instead.
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return file_pb_gdean_proto_rawDescGZIP(), []int{6}
}

func (x *ReportResponse) GetReport() *Report {
	if x != nil {
		return x.Report
	}
	return nil
}

var File_pb_gdean_proto protoreflect.FileDescriptor

var file_pb_gdean_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x62, 0x2f, 0x67, 0x64, 0x65, 0x61, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x67, 0x64, 0x65, 0x61, 0x6e, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5d, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x78, 0x45, 0x6d, 0x76, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x6d, 0x61, 0x78, 0x45, 0x6d, 0x76, 0x12, 0x3b, 0x0a, 0x0b, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x53, 0x0a, 0x06, 0x52, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x12, 0x22, 0x0a, 0x0c, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x43, 0x61, 0x6c,
	0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f,
	0x66, 0x43, 0x61, 0x6c, 0x63, 0x12, 0x25, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x67, 0x64, 0x65, 0x61, 0x6e, 0x2e, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x4a, 0x0a, 0x08,
	0x54, 0x6f, 0x77, 0x50, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x70, 0x31, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x70, 0x31, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x61, 0x74, 0x61,
	0x50, 0x31, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x06, 0x64, 0x61, 0x74, 0x61, 0x50, 0x31,
	0x12, 0x16, 0x0a, 0x06, 0x64, 0x61, 0x74, 0x61, 0x50, 0x32, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05,
	0x52, 0x06, 0x64, 0x61, 0x74, 0x61, 0x50, 0x32, 0x22, 0x3c, 0x0a, 0x0d, 0x4d, 0x61, 0x78, 0x45,
	0x6d, 0x76, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x08, 0x74, 0x6f, 0x77,
	0x50, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67, 0x64,
	0x65, 0x61, 0x6e, 0x2e, 0x54, 0x6f, 0x77, 0x50, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x74, 0x6f,
	0x77, 0x50, 0x44, 0x61, 0x74, 0x61, 0x22, 0x37, 0x0a, 0x0e, 0x4d, 0x61, 0x78, 0x45, 0x6d, 0x76,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x67, 0x64, 0x65, 0x61, 0x6e,
	0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22,
	0x0f, 0x0a, 0x0d, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x37, 0x0a, 0x0e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x25, 0x0a, 0x06, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x67, 0x64, 0x65, 0x61, 0x6e, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x52, 0x06, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x32, 0x8d, 0x01, 0x0a, 0x0c, 0x47, 0x44,
	0x65, 0x61, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x37, 0x0a, 0x06, 0x4d, 0x61,
	0x78, 0x45, 0x6d, 0x76, 0x12, 0x14, 0x2e, 0x67, 0x64, 0x65, 0x61, 0x6e, 0x2e, 0x4d, 0x61, 0x78,
	0x45, 0x6d, 0x76, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x67, 0x64, 0x65,
	0x61, 0x6e, 0x2e, 0x4d, 0x61, 0x78, 0x45, 0x6d, 0x76, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x13, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x4d, 0x61, 0x78,
	0x45, 0x6d, 0x76, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x14, 0x2e, 0x67, 0x64, 0x65,
	0x61, 0x6e, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x15, 0x2e, 0x67, 0x64, 0x65, 0x61, 0x6e, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x19, 0x5a, 0x17, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x79, 0x6e, 0x69, 0x73, 0x68, 0x69, 0x2f, 0x67,
	0x64, 0x65, 0x61, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_gdean_proto_rawDescOnce sync.Once
	file_pb_gdean_proto_rawDescData = file_pb_gdean_proto_rawDesc
)

func file_pb_gdean_proto_rawDescGZIP() []byte {
	file_pb_gdean_proto_rawDescOnce.Do(func() {
		file_pb_gdean_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_gdean_proto_rawDescData)
	})
	return file_pb_gdean_proto_rawDescData
}

var file_pb_gdean_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pb_gdean_proto_goTypes = []interface{}{
	(*Result)(nil),                // 0: gdean.Result
	(*Report)(nil),                // 1: gdean.Report
	(*TowPData)(nil),              // 2: gdean.TowPData
	(*MaxEmvRequest)(nil),         // 3: gdean.MaxEmvRequest
	(*MaxEmvResponse)(nil),        // 4: gdean.MaxEmvResponse
	(*ReportRequest)(nil),         // 5: gdean.ReportRequest
	(*ReportResponse)(nil),        // 6: gdean.ReportResponse
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_pb_gdean_proto_depIdxs = []int32{
	7, // 0: gdean.Result.create_time:type_name -> google.protobuf.Timestamp
	0, // 1: gdean.Report.result:type_name -> gdean.Result
	2, // 2: gdean.MaxEmvRequest.towPData:type_name -> gdean.TowPData
	0, // 3: gdean.MaxEmvResponse.result:type_name -> gdean.Result
	1, // 4: gdean.ReportResponse.report:type_name -> gdean.Report
	3, // 5: gdean.GDeanService.MaxEmv:input_type -> gdean.MaxEmvRequest
	5, // 6: gdean.GDeanService.ReportMaxEmvResults:input_type -> gdean.ReportRequest
	4, // 7: gdean.GDeanService.MaxEmv:output_type -> gdean.MaxEmvResponse
	6, // 8: gdean.GDeanService.ReportMaxEmvResults:output_type -> gdean.ReportResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pb_gdean_proto_init() }
func file_pb_gdean_proto_init() {
	if File_pb_gdean_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_gdean_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_gdean_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Report); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_gdean_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TowPData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_gdean_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaxEmvRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_gdean_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MaxEmvResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_gdean_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_gdean_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReportResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_gdean_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_gdean_proto_goTypes,
		DependencyIndexes: file_pb_gdean_proto_depIdxs,
		MessageInfos:      file_pb_gdean_proto_msgTypes,
	}.Build()
	File_pb_gdean_proto = out.File
	file_pb_gdean_proto_rawDesc = nil
	file_pb_gdean_proto_goTypes = nil
	file_pb_gdean_proto_depIdxs = nil
}
